//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612057_QuanLyBanHang.Model
{
    using _1612057_QuanLyBanHang.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG : BaseViewModel
    {
        int _ID_DONHANG;
        public int ID_DONHANG { get => _ID_DONHANG; set { _ID_DONHANG = value; OnPropertyChanged(); } }

        int _ID_SanPham;
        public int ID_SanPham { get => _ID_SanPham; set { _ID_SanPham = value; OnPropertyChanged(); } }

        Nullable<int> _ID_KhachHang;
        public Nullable<int> ID_KhachHang { get => _ID_KhachHang; set { _ID_KhachHang = value; OnPropertyChanged(); } }

        Nullable<int> _ID_NguoiBan;
        public Nullable<int> ID_NguoiBan { get => _ID_NguoiBan; set { _ID_NguoiBan = value; OnPropertyChanged(); } }

        int _ID_TinhTrang;
        public int ID_TinhTrang { get => _ID_TinhTrang; set { _ID_TinhTrang = value; OnPropertyChanged(); } }


        Nullable<int> _SoLuong;
        public Nullable<int> SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }

        Nullable<int> _TongTien;
        public Nullable<int> TongTien { get => _TongTien; set { _TongTien = value; OnPropertyChanged(); } }

        Nullable<System.DateTime> _NgayMua;
        public Nullable<System.DateTime> NgayMua { get => _NgayMua; set { _NgayMua = value; OnPropertyChanged(); } }

        Nullable<int> _IsDelete;
        public Nullable<int> IsDelete { get => _IsDelete; set { _IsDelete = value; OnPropertyChanged(); } }


        private  KHACHHANG _KHACHHANG;
        public virtual KHACHHANG KHACHHANG { get => _KHACHHANG; set { _KHACHHANG = value; OnPropertyChanged(); } }

        private QUANTRIVIEN _QUANTRIVIEN;
        public virtual QUANTRIVIEN QUANTRIVIEN { get => _QUANTRIVIEN; set { _QUANTRIVIEN = value; OnPropertyChanged(); } }

        private SANPHAM _SANPHAM;
        public virtual SANPHAM SANPHAM { get => _SANPHAM; set { _SANPHAM = value; OnPropertyChanged(); } }

        private TINHTRANG _TINHTRANG;
        public virtual TINHTRANG TINHTRANG { get => _TINHTRANG; set { _TINHTRANG = value; OnPropertyChanged(); } }

        //public virtual KHACHHANG KHACHHANG { get; set; }
        //public virtual QUANTRIVIEN QUANTRIVIEN { get; set; }
        //public virtual SANPHAM SANPHAM { get; set; }
        //public virtual TINHTRANG TINHTRANG { get; set; }
    }
}
