//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1612057_QuanLyBanHang.Model
{
    using _1612057_QuanLyBanHang.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM :BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }

        int _ID_SANPHAM;
        public int ID_SANPHAM { get => _ID_SANPHAM; set { _ID_SANPHAM = value; OnPropertyChanged(); } }

        Nullable<int> _ID_LoaiSanPham;
        public Nullable<int> ID_LoaiSanPham { get => _ID_LoaiSanPham; set { _ID_LoaiSanPham = value; OnPropertyChanged(); } }

        string _ID_KhuyenMai;
        public string ID_KhuyenMai { get => _ID_KhuyenMai; set { _ID_KhuyenMai = value; OnPropertyChanged(); } }

        string _TenSanPham;
        public string TenSanPham { get => _TenSanPham; set { _TenSanPham = value; OnPropertyChanged(); } }

        string _HangSanXuat;
        public string HangSanXuat { get => _HangSanXuat; set { _HangSanXuat = value; OnPropertyChanged(); } }

        Nullable<int> _GiaTien;
        public Nullable<int> GiaTien { get => _GiaTien; set { _GiaTien = value; OnPropertyChanged(); } }

        string _MoTa;
        public string MoTa { get => _MoTa; set { _MoTa = value; OnPropertyChanged(); } }

        Nullable<int> _SoLuotMua;
        public Nullable<int> SoLuotMua { get => _SoLuotMua; set { _SoLuotMua = value; OnPropertyChanged(); } }

        Nullable<int> _SoLuongCon;
        public Nullable<int> SoLuongCon { get => _SoLuongCon; set { _SoLuongCon = value; OnPropertyChanged(); } }

        Nullable<int> _GiaNhap;
        public Nullable<int> GiaNhap { get => _GiaNhap; set { _GiaNhap = value; OnPropertyChanged(); } }

        Nullable<int> _IsDelete;
        public Nullable<int> IsDelete { get => _IsDelete; set { _IsDelete = value; OnPropertyChanged(); } }


        //public int ID_SANPHAM { get; set; }
        //public Nullable<int> ID_LoaiSanPham { get; set; }
        //public string ID_KhuyenMai { get; set; }
        //public string TenSanPham { get; set; }
        //public string HangSanXuat { get; set; }
        //public Nullable<int> GiaTien { get; set; }
        //public string MoTa { get; set; }
        //public Nullable<int> SoLuotMua { get; set; }
        //public Nullable<int> SoLuongCon { get; set; }
        //public Nullable<int> GiaNhap { get; set; }
        //public Nullable<int> IsDelete { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        ICollection<DONHANG> _DONHANGs;
        public virtual ICollection<DONHANG> DONHANGs { get => _DONHANGs; set { _DONHANGs = value; OnPropertyChanged(); } }

        KHUYENMAI _KHUYENMAI;
        public virtual KHUYENMAI KHUYENMAI { get => _KHUYENMAI; set { _KHUYENMAI = value; OnPropertyChanged(); } }

        LOAISANPHAM _LOAISANPHAM;
        public virtual LOAISANPHAM LOAISANPHAM { get => _LOAISANPHAM; set { _LOAISANPHAM = value; OnPropertyChanged(); } }

        //public virtual ICollection<DONHANG> DONHANGs { get; set; }
        //public virtual KHUYENMAI KHUYENMAI { get; set; }
        //public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
